export const PRESET_ACTIONS = {
  GET_ALL_EFFECTS_ASYNC: 'GET_ALL_EFFECTS_ASYNC',
  GET_ALL_INSTRUMENTS_ASYNC: 'GET_ALL_INSTRUMENTS_ASYNC',
  GET_ALL_PATTERNS_ASYNC: 'GET_ALL_PATTERNS_ASYNC',
  GET_ALL_PRESETS_ASYNC: 'GET_ALL_PRESETS_ASYNC',
};
